FROM tensorflow/tensorflow:2.9.1

RUN apt-get update && \
    apt-get install ffmpeg libsm6 libxext6  -y

RUN python -m pip install --upgrade pip
COPY docker/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt


WORKDIR /opt/app
COPY . .
